### ISSUE TITLE
Japanese-Alpaca-LoRA のライセンスについて

### ISSUE THREAD

**Issue by akeyhero** [masanorihirano/llm-japanese-dataset#73]
素晴らしいデータセットをありがとうございます。

Japanese-Alpaca-LoRA のライセンスについてですが、大元の Stanford Alpaca が CC BY-NC 4.0 であるため、
本来的には [CC BY-NC 4.0 かそれ以上と見做すのが適切](https://creativecommons.jp/faq/#c10)ではないかと思います。

また、 CC BY-NC 4.0 とは明記されていませんが、

> In accordance with other models being referenced, this model is not available for commercial use and can only be used for research purposes.

と言う[記載](https://github.com/masa3141/japanese-alpaca-lora)もあります (モデルではないですが)。

[CC BY-SA と CC BY-NC (またはそれ以上) は混合することができない](https://creativecommons.jp/faq/#c9)ので、
残念ながら、当データセットを CC BY-SA 4.0 で頒布するためには Japanese-Alpaca-LoRA を除外するべきではないかと考えます。
ご検討をお願いいたします。

**Comment by masanorihirano** [comment]
原則として，LICENSE.mdをマスターとして判断を行っておりますが，Alpacaについてのこの問題は把握をしております．

まだまだ通説レベルでしか議論がなされていないので，こちらも対処に悩んでいるところです．なお，NCが確定的であれば，間違いなくデータセットからdropします．

ただし，Alpaca側の記載も当初から変化している気がするので，再度確認して，追加の判断材料にしたいと思います．

もし，わかる範囲で以下，教えていただけますでしょうか？

 - 「Stanford Alpaca が CC-BY-NC 4.0 であるため」とのことでしたが，ライセンスの記載場所を教えていただけますでしょうか？
 -  ChatGPTが出力したデータを競合モデルに使用してはいけないというtermsがありますが，これは，ChatGPTの利用者当人には間違いなく適用されると思います．しかし，そのtermsはchatGPTの直接利用者ではない場合に，データセットを通じて適用されると解釈できるのでしょうか？

**Comment by masanorihirano** [comment]
前者については確認できました．
5/15に変更されているのですね．

https://github.com/tatsu-lab/stanford_alpaca/commit/7ad0c6b4f75c7365aca85bda8ad8fbc24915c7ed

**Comment by masanorihirano** [comment]
変更を踏まえ，dropすることを内部決定しました．(これから反映します)

**Comment by masanorihirano** [comment]
dropしました．v1.0.1にて反映されます．

**Comment by akeyhero** [comment]
早速のご対応ありがとうございます。

**Comment by akeyhero** [comment]
ChatGPT に関しては当方も法律の専門家ではないので分かりかねますが、倫理的に問題がある点で曰くがつくとは思います。
